{
 "title": "Full Overview",
 "tags": [ "screeps" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "user", "query": "screeps.*" },
   { "name": "shard", "query": "screeps.$user.*" },
   { "name": "room", "query": "screeps.$user.$shard.room.*" }
  ]
 },
 "panels": [
  { "title": "CPU for $shard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "shard" },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms", "label": "Usage" }
   ],
   "targets": [
    {
     "target": "alias(screeps.$user.$shard.cpu.used, 'Used')"
    },
    {
     "target": "alias(screeps.$user.$shard.cpu.bucket, 'Bucket')"
    },
    {
     "target": "alias(screeps.$user.$shard.cpu.limit, 'Limit')"
    }
   ]
  },
  {
   "title": "Current Bucket",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "screeps.$user.$shard.cpu.bucket"
    }
   ]
  },
  {
   "title": "Ticks Per Stats Update",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(derivative(screeps.$user.$shard.time), 'Ticks Per Update')"
    }
   ]
  },
  { "title": "GCL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "GCL",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "screeps.$user.$shard.gcl.level" }
   ]
  },
  {
   "title": "GCL Progress",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(screeps.$user.$shard.gcl.progress, #B)"
    }
   ]
  },
  {
   "title": "Time to Next GCL",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(diffSeries(screeps.$user.$shard.gcl.progress_total, #B), #C)"
    }
   ]
  },
  {
   "title": "GCL Upgrade",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(divideSeries(nonNegativeDerivative(screeps.$user.$shard.gcl.progress), #B), 'GCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(screeps.$user.$shard.gcl.progress), #B), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "Global Stored Energy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(screeps.$user.$shard.rooms.*.energy_available), 'Spawns and Extensions')"
    },
    {
     "target": "alias(sumSeries(screeps.$user.$shard.rooms.*.storage_energy), 'Storage')"
    },
    {
     "target": "alias(sumSeries(screeps.$user.$shard.rooms.*.terminal_energy), 'Terminals')"
    },
    {
     "target": "alias(sumSeries(#A, #B, #C), \"Total\")"
    }
   ]
  },
  { "title": "$room", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "room" },
  {
   "title": "RCL",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "screeps.$user.$shard.rooms.$room.controller_level"
    }
   ]
  },
  {
   "title": "RCL progress",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 18 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(screeps.$user.$shard.rooms.$room.controller_progress, #B)"
    }
   ]
  },
  {
   "title": "Time to Next RCL",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 18 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(diffSeries(screeps.$user.$shard.rooms.$room.controller_progress_total, #B), #C)"
    }
   ]
  },
  {
   "title": "RCL Upgrade",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(divideSeries(nonNegativeDerivative(screeps.$user.$shard.rooms.$room.controller_progress), #C), 'RCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(screeps.$user.$shard.rooms.$room.controller_progress), #C), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "Room Stored Energy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(screeps.$user.$shard.rooms.$room.energy_available, 'Spawns and Extensions')"
    },
    {
     "target": "alias(screeps.$user.$shard.rooms.$room.storage_energy, 'Storage')"
    },
    {
     "target": "alias(screeps.$user.$shard.rooms.$room.terminal_energy, 'Terminal')"
    },
    {
     "target": "alias(sumSeries(#A, #B, #C), \"Total\")"
    }
   ]
  },
  { "title": "$room", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "RCL",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "screeps.$user.$shard.rooms.$room.controller_level"
    }
   ]
  },
  {
   "title": "RCL progress",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 27 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(screeps.$user.$shard.rooms.$room.controller_progress, #B)"
    }
   ]
  },
  {
   "title": "Time to Next RCL",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 27 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(diffSeries(screeps.$user.$shard.rooms.$room.controller_progress_total, #B), #C)"
    }
   ]
  },
  {
   "title": "RCL Upgrade",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(divideSeries(nonNegativeDerivative(screeps.$user.$shard.rooms.$room.controller_progress), #C), 'RCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(screeps.$user.$shard.rooms.$room.controller_progress), #C), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "Room Stored Energy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(screeps.$user.$shard.rooms.$room.energy_available, 'Spawns and Extensions')"
    },
    {
     "target": "alias(screeps.$user.$shard.rooms.$room.storage_energy, 'Storage')"
    },
    {
     "target": "alias(screeps.$user.$shard.rooms.$room.terminal_energy, 'Terminal')"
    },
    {
     "target": "alias(sumSeries(#A, #B, #C), \"Total\")"
    }
   ]
  }
 ]
}