{
 "title": "Full Overview",
 "tags": [ "screeps" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "user", "query": "screeps.*" },
   { "name": "shard", "query": "screeps.$user.shard.*" },
   {
    "name": "room",
    "query": "screeps.$user.shard.$shard.room.*"
   }
  ]
 },
 "panels": [
  { "title": "CPU for $shard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "shard" },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms", "label": "Usage" }
   ],
   "targets": [
    {
     "target": "alias(screeps.$user.shard.$shard.cpu.used, 'Used')"
    },
    {
     "target": "alias(movingAverage(screeps.$user.shard.$shard.cpu.used, '10min'), 'Average Used')"
    },
    {
     "target": "alias(screeps.$user.shard.$shard.cpu.bucket, 'Bucket')"
    },
    {
     "target": "alias(screeps.$user.shard.$shard.cpu.limit, 'Limit')"
    }
   ]
  },
  {
   "title": "Current Bucket",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "screeps.$user.shard.$shard.cpu.bucket"
    }
   ]
  },
  {
   "title": "Ticks Per Stats Update",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(derivative(screeps.$user.shard.$shard.time), 'Ticks Per Update')"
    }
   ]
  },
  { "title": "GCL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "GCL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "screeps.$user.shard.$shard.gcl.level"
    }
   ]
  },
  {
   "title": "GCL Upgrade",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.gcl.progress, 100)), #B), 'GCL per tick')",
     "targetFull": "alias(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.gcl.progress, 100)), derivative(screeps.$user.shard.$shard.time)), 'GCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.gcl.progress, 100)), #B), '1hour'), '1hr Moving Average')",
     "targetFull": "alias(movingAverage(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.gcl.progress, 100)), derivative(screeps.$user.shard.$shard.time)), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "Global Stored Energy",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "groupByNode(screeps.$user.shard.$shard.room.*.storage.*.energy, 7, \"sumSeries\")"
    },
    {
     "target": "alias(sumSeries(#B), 'Total')",
     "targetFull": "alias(sumSeries(groupByNode(screeps.$user.shard.$shard.room.*.storage.*.energy, 7, \"sumSeries\")), 'Total')"
    }
   ]
  },
  {
   "title": "Global Resources",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "groupByNode(screeps.$user.shard.$shard.room.*.storage.*.*, 8, \"sumSeries\")"
    }
   ]
  },
  {
   "title": "Credits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(divideSeries(derivative(keepLastValue(screeps.$user.shard.$shard.market.credits, 100)), #B), 'Credits per tick')",
     "targetFull": "alias(divideSeries(derivative(keepLastValue(screeps.$user.shard.$shard.market.credits, 100)), derivative(screeps.$user.shard.$shard.time)), 'Credits per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(derivative(keepLastValue(screeps.$user.shard.$shard.market.credits, 100)), #B), '1hour'), '1 Hour Moving Average')",
     "targetFull": "alias(movingAverage(divideSeries(derivative(keepLastValue(screeps.$user.shard.$shard.market.credits, 100)), derivative(screeps.$user.shard.$shard.time)), '1hour'), '1 Hour Moving Average')"
    },
    {
     "refCount": 2,
     "target": "alias(keepLastValue(screeps.$user.shard.$shard.market.credits, 100), 'Total')"
    }
   ]
  },
  {
   "title": "GCL Progress",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(screeps.$user.shard.$shard.gcl.progress, #B)"
    }
   ]
  },
  {
   "title": "Time to Next GCL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 15 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(diffSeries(keepLastValue(screeps.$user.shard.$shard.gcl.progress_total, 100), #B), #C)",
     "targetFull": "divideSeries(diffSeries(keepLastValue(screeps.$user.shard.$shard.gcl.progress_total, 100), keepLastValue(screeps.$user.shard.$shard.gcl.progress, 100)), scaleToSeconds(movingAverage(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.gcl.progress, 100)), '1hour'), 1))"
    }
   ]
  },
  { "title": "$room", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }, "repeat": "room" },
  {
   "title": "RCL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "screeps.$user.shard.$shard.room.$room.controller_level"
    }
   ]
  },
  {
   "title": "RCL Upgrade",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 4, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), #C), 'RCL per tick')",
     "targetFull": "alias(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), derivative(screeps.$user.shard.$shard.time)), 'RCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), #C), '1hour'), '1hr Moving Average')",
     "targetFull": "alias(movingAverage(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), derivative(screeps.$user.shard.$shard.time)), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "Room Stored Energy",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 10, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "groupByNode(screeps.$user.shard.$shard.room.$room.storage.*.energy, 7, \"sumSeries\")"
    },
    {
     "target": "alias(sumSeries(#A), \"Total\")",
     "targetFull": "alias(sumSeries(groupByNode(screeps.$user.shard.$shard.room.$room.storage.*.energy, 7, \"sumSeries\")), \"Total\")"
    }
   ]
  },
  {
   "title": "Room Resources",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 15, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "groupByNode(screeps.$user.shard.$shard.room.$room.storage.*.*, 8, \"sumSeries\")"
    },
    {
     "target": "alias(sumSeries(#A), \"Total\")",
     "targetFull": "alias(sumSeries(groupByNode(screeps.$user.shard.$shard.room.$room.storage.*.*, 8, \"sumSeries\")), \"Total\")"
    }
   ]
  },
  {
   "title": "RCL progress",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(screeps.$user.shard.$shard.room.$room.controller_progress, #B)"
    }
   ]
  },
  {
   "title": "Time to Next RCL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 26 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(diffSeries(screeps.$user.shard.$shard.room.$room.controller_progress_total, #B), #C)",
     "targetFull": "divideSeries(diffSeries(screeps.$user.shard.$shard.room.$room.controller_progress_total, keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), scaleToSeconds(movingAverage(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), '1hour'), 1))"
    }
   ]
  },
  { "title": "$room", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "RCL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "screeps.$user.shard.$shard.room.$room.controller_level"
    }
   ]
  },
  {
   "title": "RCL Upgrade",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 4, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), #C), 'RCL per tick')",
     "targetFull": "alias(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), derivative(screeps.$user.shard.$shard.time)), 'RCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), #C), '1hour'), '1hr Moving Average')",
     "targetFull": "alias(movingAverage(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), derivative(screeps.$user.shard.$shard.time)), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "Room Stored Energy",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 10, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "groupByNode(screeps.$user.shard.$shard.room.$room.storage.*.energy, 7, \"sumSeries\")"
    },
    {
     "target": "alias(sumSeries(#A), \"Total\")",
     "targetFull": "alias(sumSeries(groupByNode(screeps.$user.shard.$shard.room.$room.storage.*.energy, 7, \"sumSeries\")), \"Total\")"
    }
   ]
  },
  {
   "title": "Room Resources",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 15, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "groupByNode(screeps.$user.shard.$shard.room.$room.storage.*.*, 8, \"sumSeries\")"
    },
    {
     "target": "alias(sumSeries(#A), \"Total\")",
     "targetFull": "alias(sumSeries(groupByNode(screeps.$user.shard.$shard.room.$room.storage.*.*, 8, \"sumSeries\")), \"Total\")"
    }
   ]
  },
  {
   "title": "RCL progress",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 33 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(screeps.$user.shard.$shard.room.$room.controller_progress, #B)"
    }
   ]
  },
  {
   "title": "Time to Next RCL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 37 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(diffSeries(screeps.$user.shard.$shard.room.$room.controller_progress_total, #B), #C)",
     "targetFull": "divideSeries(diffSeries(screeps.$user.shard.$shard.room.$room.controller_progress_total, keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), scaleToSeconds(movingAverage(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), '1hour'), 1))"
    }
   ]
  },
  { "title": "$room", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "RCL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 41 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "screeps.$user.shard.$shard.room.$room.controller_level"
    }
   ]
  },
  {
   "title": "RCL Upgrade",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 4, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), #C), 'RCL per tick')",
     "targetFull": "alias(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), derivative(screeps.$user.shard.$shard.time)), 'RCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), #C), '1hour'), '1hr Moving Average')",
     "targetFull": "alias(movingAverage(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), derivative(screeps.$user.shard.$shard.time)), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "Room Stored Energy",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 10, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "groupByNode(screeps.$user.shard.$shard.room.$room.storage.*.energy, 7, \"sumSeries\")"
    },
    {
     "target": "alias(sumSeries(#A), \"Total\")",
     "targetFull": "alias(sumSeries(groupByNode(screeps.$user.shard.$shard.room.$room.storage.*.energy, 7, \"sumSeries\")), \"Total\")"
    }
   ]
  },
  {
   "title": "Room Resources",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 15, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "groupByNode(screeps.$user.shard.$shard.room.$room.storage.*.*, 8, \"sumSeries\")"
    },
    {
     "target": "alias(sumSeries(#A), \"Total\")",
     "targetFull": "alias(sumSeries(groupByNode(screeps.$user.shard.$shard.room.$room.storage.*.*, 8, \"sumSeries\")), \"Total\")"
    }
   ]
  },
  {
   "title": "RCL progress",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 44 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(screeps.$user.shard.$shard.room.$room.controller_progress, #B)"
    }
   ]
  },
  {
   "title": "Time to Next RCL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 48 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(diffSeries(screeps.$user.shard.$shard.room.$room.controller_progress_total, #B), #C)",
     "targetFull": "divideSeries(diffSeries(screeps.$user.shard.$shard.room.$room.controller_progress_total, keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), scaleToSeconds(movingAverage(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), '1hour'), 1))"
    }
   ]
  },
  { "title": "$room", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "RCL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 52 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "screeps.$user.shard.$shard.room.$room.controller_level"
    }
   ]
  },
  {
   "title": "RCL Upgrade",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 4, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), #C), 'RCL per tick')",
     "targetFull": "alias(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), derivative(screeps.$user.shard.$shard.time)), 'RCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), #C), '1hour'), '1hr Moving Average')",
     "targetFull": "alias(movingAverage(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), derivative(screeps.$user.shard.$shard.time)), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "Room Stored Energy",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 10, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "groupByNode(screeps.$user.shard.$shard.room.$room.storage.*.energy, 7, \"sumSeries\")"
    },
    {
     "target": "alias(sumSeries(#A), \"Total\")",
     "targetFull": "alias(sumSeries(groupByNode(screeps.$user.shard.$shard.room.$room.storage.*.energy, 7, \"sumSeries\")), \"Total\")"
    }
   ]
  },
  {
   "title": "Room Resources",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 15, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "groupByNode(screeps.$user.shard.$shard.room.$room.storage.*.*, 8, \"sumSeries\")"
    },
    {
     "target": "alias(sumSeries(#A), \"Total\")",
     "targetFull": "alias(sumSeries(groupByNode(screeps.$user.shard.$shard.room.$room.storage.*.*, 8, \"sumSeries\")), \"Total\")"
    }
   ]
  },
  {
   "title": "RCL progress",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 55 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(screeps.$user.shard.$shard.room.$room.controller_progress, #B)"
    }
   ]
  },
  {
   "title": "Time to Next RCL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 59 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(diffSeries(screeps.$user.shard.$shard.room.$room.controller_progress_total, #B), #C)",
     "targetFull": "divideSeries(diffSeries(screeps.$user.shard.$shard.room.$room.controller_progress_total, keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), scaleToSeconds(movingAverage(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), '1hour'), 1))"
    }
   ]
  },
  { "title": "$room", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "RCL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 63 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "screeps.$user.shard.$shard.room.$room.controller_level"
    }
   ]
  },
  {
   "title": "RCL Upgrade",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 4, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), #C), 'RCL per tick')",
     "targetFull": "alias(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), derivative(screeps.$user.shard.$shard.time)), 'RCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), #C), '1hour'), '1hr Moving Average')",
     "targetFull": "alias(movingAverage(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), derivative(screeps.$user.shard.$shard.time)), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "Room Stored Energy",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 10, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "groupByNode(screeps.$user.shard.$shard.room.$room.storage.*.energy, 7, \"sumSeries\")"
    },
    {
     "target": "alias(sumSeries(#A), \"Total\")",
     "targetFull": "alias(sumSeries(groupByNode(screeps.$user.shard.$shard.room.$room.storage.*.energy, 7, \"sumSeries\")), \"Total\")"
    }
   ]
  },
  {
   "title": "Room Resources",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 15, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "groupByNode(screeps.$user.shard.$shard.room.$room.storage.*.*, 8, \"sumSeries\")"
    },
    {
     "target": "alias(sumSeries(#A), \"Total\")",
     "targetFull": "alias(sumSeries(groupByNode(screeps.$user.shard.$shard.room.$room.storage.*.*, 8, \"sumSeries\")), \"Total\")"
    }
   ]
  },
  {
   "title": "RCL progress",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 66 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(screeps.$user.shard.$shard.room.$room.controller_progress, #B)"
    }
   ]
  },
  {
   "title": "Time to Next RCL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 70 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(diffSeries(screeps.$user.shard.$shard.room.$room.controller_progress_total, #B), #C)",
     "targetFull": "divideSeries(diffSeries(screeps.$user.shard.$shard.room.$room.controller_progress_total, keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), scaleToSeconds(movingAverage(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), '1hour'), 1))"
    }
   ]
  },
  { "title": "$room", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "RCL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 74 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "screeps.$user.shard.$shard.room.$room.controller_level"
    }
   ]
  },
  {
   "title": "RCL Upgrade",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 4, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), #C), 'RCL per tick')",
     "targetFull": "alias(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), derivative(screeps.$user.shard.$shard.time)), 'RCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), #C), '1hour'), '1hr Moving Average')",
     "targetFull": "alias(movingAverage(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), derivative(screeps.$user.shard.$shard.time)), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "Room Stored Energy",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 10, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "groupByNode(screeps.$user.shard.$shard.room.$room.storage.*.energy, 7, \"sumSeries\")"
    },
    {
     "target": "alias(sumSeries(#A), \"Total\")",
     "targetFull": "alias(sumSeries(groupByNode(screeps.$user.shard.$shard.room.$room.storage.*.energy, 7, \"sumSeries\")), \"Total\")"
    }
   ]
  },
  {
   "title": "Room Resources",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 15, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "groupByNode(screeps.$user.shard.$shard.room.$room.storage.*.*, 8, \"sumSeries\")"
    },
    {
     "target": "alias(sumSeries(#A), \"Total\")",
     "targetFull": "alias(sumSeries(groupByNode(screeps.$user.shard.$shard.room.$room.storage.*.*, 8, \"sumSeries\")), \"Total\")"
    }
   ]
  },
  {
   "title": "RCL progress",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 77 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(screeps.$user.shard.$shard.room.$room.controller_progress, #B)"
    }
   ]
  },
  {
   "title": "Time to Next RCL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 81 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(diffSeries(screeps.$user.shard.$shard.room.$room.controller_progress_total, #B), #C)",
     "targetFull": "divideSeries(diffSeries(screeps.$user.shard.$shard.room.$room.controller_progress_total, keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), scaleToSeconds(movingAverage(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), '1hour'), 1))"
    }
   ]
  },
  { "title": "$room", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "RCL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 85 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "screeps.$user.shard.$shard.room.$room.controller_level"
    }
   ]
  },
  {
   "title": "RCL Upgrade",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 4, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), #C), 'RCL per tick')",
     "targetFull": "alias(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), derivative(screeps.$user.shard.$shard.time)), 'RCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), #C), '1hour'), '1hr Moving Average')",
     "targetFull": "alias(movingAverage(divideSeries(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), derivative(screeps.$user.shard.$shard.time)), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "Room Stored Energy",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 10, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "groupByNode(screeps.$user.shard.$shard.room.$room.storage.*.energy, 7, \"sumSeries\")"
    },
    {
     "target": "alias(sumSeries(#A), \"Total\")",
     "targetFull": "alias(sumSeries(groupByNode(screeps.$user.shard.$shard.room.$room.storage.*.energy, 7, \"sumSeries\")), \"Total\")"
    }
   ]
  },
  {
   "title": "Room Resources",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 15, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "groupByNode(screeps.$user.shard.$shard.room.$room.storage.*.*, 8, \"sumSeries\")"
    },
    {
     "target": "alias(sumSeries(#A), \"Total\")",
     "targetFull": "alias(sumSeries(groupByNode(screeps.$user.shard.$shard.room.$room.storage.*.*, 8, \"sumSeries\")), \"Total\")"
    }
   ]
  },
  {
   "title": "RCL progress",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 88 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(screeps.$user.shard.$shard.room.$room.controller_progress, #B)"
    }
   ]
  },
  {
   "title": "Time to Next RCL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 92 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(diffSeries(screeps.$user.shard.$shard.room.$room.controller_progress_total, #B), #C)",
     "targetFull": "divideSeries(diffSeries(screeps.$user.shard.$shard.room.$room.controller_progress_total, keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), scaleToSeconds(movingAverage(nonNegativeDerivative(keepLastValue(screeps.$user.shard.$shard.room.$room.controller_progress, 100)), '1hour'), 1))"
    }
   ]
  }
 ]
}