{
 "title": "Screeps Overview",
 "tags": [ "screeps" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "user", "query": "data.screeps_com.*" },
   { "name": "shard", "query": "data.screeps_com.$user.shard.*" },
   {
    "name": "room",
    "query": "data.screeps_com.$user.shard.$shard.room.*"
   }
  ]
 },
 "panels": [
  { "title": "Global Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GCL Level",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "data.screeps_com.$user.shard.$shard.gcl.level"
    }
   ]
  },
  {
   "title": "GCL Progress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "targets": [
    {
     "target": "divideSeries(data.screeps_com.$user.shard.$shard.gcl.progress, #B)"
    }
   ]
  },
  {
   "title": "Time to Next GCL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "targets": [
    {
     "target": "divideSeries(diffSeries(keepLastValue(data.screeps_com.$user.shard.$shard.gcl.progress_total, 100), #B), #C)",
     "targetFull": "divideSeries(diffSeries(keepLastValue(data.screeps_com.$user.shard.$shard.gcl.progress_total, 100), keepLastValue(data.screeps_com.$user.shard.$shard.gcl.progress, 100)), scaleToSeconds(movingAverage(nonNegativeDerivative(keepLastValue(data.screeps_com.$user.shard.$shard.gcl.progress, 100)), '1hour'), 1))"
    }
   ]
  },
  {
   "title": "GCL Upgrade Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 1 },
   "targets": [
    {
     "target": "alias(divideSeries(nonNegativeDerivative(keepLastValue(data.screeps_com.$user.shard.$shard.gcl.progress, 100)), #B), 'GCL per tick')",
     "targetFull": "alias(divideSeries(nonNegativeDerivative(keepLastValue(data.screeps_com.$user.shard.$shard.gcl.progress, 100)), derivative(data.screeps_com.$user.shard.$shard.time)), 'GCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(keepLastValue(data.screeps_com.$user.shard.$shard.gcl.progress, 100)), #B), '1hour'), '1hr Moving Average')",
     "targetFull": "alias(movingAverage(divideSeries(nonNegativeDerivative(keepLastValue(data.screeps_com.$user.shard.$shard.gcl.progress, 100)), derivative(data.screeps_com.$user.shard.$shard.time)), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "GPL Level",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "targets": [
    {
     "target": "data.screeps_com.$user.shard.$shard.gpl.level"
    }
   ]
  },
  {
   "title": "GPL Progress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "targets": [
    {
     "target": "divideSeries(data.screeps_com.$user.shard.$shard.gpl.progress, #B)"
    }
   ]
  },
  {
   "title": "Credits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "targets": [
    {
     "target": "alias(keepLastValue(data.screeps_com.$user.shard.$shard.market.credits, 100), 'Credits')"
    }
   ]
  },
  {
   "title": "Credits Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 4 },
   "targets": [
    {
     "target": "alias(divideSeries(derivative(keepLastValue(data.screeps_com.$user.shard.$shard.market.credits, 100)), #B), 'Credits per tick')",
     "targetFull": "alias(divideSeries(derivative(keepLastValue(data.screeps_com.$user.shard.$shard.market.credits, 100)), derivative(data.screeps_com.$user.shard.$shard.time)), 'Credits per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(derivative(keepLastValue(data.screeps_com.$user.shard.$shard.market.credits, 100)), #B), '1hour'), '1hr Moving Average')",
     "targetFull": "alias(movingAverage(divideSeries(derivative(keepLastValue(data.screeps_com.$user.shard.$shard.market.credits, 100)), derivative(data.screeps_com.$user.shard.$shard.time)), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "Global Stored Energy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "groupByNode(data.screeps_com.$user.shard.$shard.room.*.storage.*.energy, 7, \"sumSeries\")"
    },
    {
     "target": "alias(sumSeries(#B), 'Total')",
     "targetFull": "alias(sumSeries(groupByNode(data.screeps_com.$user.shard.$shard.room.*.storage.*.energy, 7, \"sumSeries\")), 'Total')"
    }
   ]
  },
  {
   "title": "Global Resources",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "target": "groupByNode(data.screeps_com.$user.shard.$shard.room.*.storage.*.*, 8, \"sumSeries\")"
    }
   ]
  },
  {
   "title": "Ticks Per Stats Update",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "target": "alias(derivative(data.screeps_com.$user.shard.$shard.time), 'Ticks Per Update')"
    }
   ]
  },
  { "title": "Shard: $shard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }, "repeat": "shard" },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "target": "alias(data.screeps_com.$user.shard.$shard.cpu.used, 'Used')"
    },
    {
     "target": "alias(movingAverage(data.screeps_com.$user.shard.$shard.cpu.used, '10min'), 'Average Used')"
    },
    {
     "target": "alias(data.screeps_com.$user.shard.$shard.cpu.bucket, 'Bucket')"
    },
    {
     "target": "alias(data.screeps_com.$user.shard.$shard.cpu.limit, 'Limit')"
    }
   ]
  },
  {
   "title": "CPU Bucket",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 16 },
   "targets": [
    {
     "target": "data.screeps_com.$user.shard.$shard.cpu.bucket"
    }
   ]
  },
  {
   "title": "Total Creeps",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 16 },
   "targets": [
    {
     "target": "alias(countSeries(data.screeps_com.$user.shard.$shard.room.*), 'Rooms')"
    }
   ]
  },
  {
   "title": "Game Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 16 },
   "targets": [
    {
     "target": "data.screeps_com.$user.shard.$shard.time"
    }
   ]
  },
  { "title": "$room", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }, "repeat": "room" },
  {
   "title": "RCL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 24 },
   "targets": [
    {
     "target": "data.screeps_com.$user.shard.$shard.room.$room.controller_level"
    }
   ]
  },
  {
   "title": "RCL Progress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 24 },
   "targets": [
    {
     "target": "divideSeries(data.screeps_com.$user.shard.$shard.room.$room.controller_progress, #B)"
    }
   ]
  },
  {
   "title": "Time to Next RCL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 24 },
   "targets": [
    {
     "target": "divideSeries(diffSeries(data.screeps_com.$user.shard.$shard.room.$room.controller_progress_total, #B), #C)",
     "targetFull": "divideSeries(diffSeries(data.screeps_com.$user.shard.$shard.room.$room.controller_progress_total, keepLastValue(data.screeps_com.$user.shard.$shard.room.$room.controller_progress, 100)), scaleToSeconds(movingAverage(nonNegativeDerivative(keepLastValue(data.screeps_com.$user.shard.$shard.room.$room.controller_progress, 100)), '1hour'), 1))"
    }
   ]
  },
  {
   "title": "RCL Upgrade Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 24 },
   "targets": [
    {
     "target": "alias(divideSeries(nonNegativeDerivative(keepLastValue(data.screeps_com.$user.shard.$shard.room.$room.controller_progress, 100)), #C), 'RCL per tick')",
     "targetFull": "alias(divideSeries(nonNegativeDerivative(keepLastValue(data.screeps_com.$user.shard.$shard.room.$room.controller_progress, 100)), derivative(data.screeps_com.$user.shard.$shard.time)), 'RCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(keepLastValue(data.screeps_com.$user.shard.$shard.room.$room.controller_progress, 100)), #C), '1hour'), '1hr Moving Average')",
     "targetFull": "alias(movingAverage(divideSeries(nonNegativeDerivative(keepLastValue(data.screeps_com.$user.shard.$shard.room.$room.controller_progress, 100)), derivative(data.screeps_com.$user.shard.$shard.time)), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "Room Stored Energy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 24 },
   "targets": [
    {
     "target": "groupByNode(data.screeps_com.$user.shard.$shard.room.$room.storage.*.energy, 7, \"sumSeries\")"
    },
    {
     "target": "alias(sumSeries(#A), \"Total\")",
     "targetFull": "alias(sumSeries(groupByNode(data.screeps_com.$user.shard.$shard.room.$room.storage.*.energy, 7, \"sumSeries\")), \"Total\")"
    }
   ]
  },
  {
   "title": "Room Resources",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 24 },
   "targets": [
    {
     "target": "groupByNode(data.screeps_com.$user.shard.$shard.room.$room.storage.*.*, 8, \"sumSeries\")"
    }
   ]
  },
  {
   "title": "Energy Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 27 },
   "targets": [
    {
     "target": "alias(data.screeps_com.$user.shard.$shard.room.$room.energy_available, 'Available')"
    },
    {
     "target": "alias(data.screeps_com.$user.shard.$shard.room.$room.energy_capacity_available, 'Capacity')"
    }
   ]
  },
  {
   "title": "Energy Fill",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 27 },
   "targets": [
    {
     "target": "divideSeries(data.screeps_com.$user.shard.$shard.room.$room.energy_available, #B)"
    }
   ]
  }
 ]
}